[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "fastapi",
  "uvicorn[standard]"
]

[tool.uv.sources]

[project.scripts]
api = "api.__main__:main"

[project.optional-dependencies]
test = [
  "behave>=1.2.6",
  "pytest>=8.3",
  "httpx>=0.27",
]